### ISSUE TITLE
How do I know if the value corresponds to the original key

### ISSUE THREAD

**Issue by eric49861** [rosedblabs/diskhash#6]
I have a problem with one point, which I think is design flaws.
When I want to query some value from the hashtable, I can do this by running hashtable.Get(key, func(Slot)(bool,error))... But due to hash collisions, there may be many values associated with the hashcode of the current key, but the original key is not stored in the slot, so with a MatchFunc function, how can the user know if it is a match?
The above point is my doubt, and I have also done relevant tests.

**Comment by roseduan** [comment]
Can you show me some example code?

The hash table is a Linear Hashing algorithm, see https://en.wikipedia.org/wiki/Linear_hashing
